version = 0.1

[default.deploy.parameters]
stack_name = "tweeter-server"
s3_bucket = "tychart-s3-tweeter-lambdas"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []